In [5]:
import gym
import random
import numpy as np

# Create environment
env = gym.make("FrozenLake-v1", is_slippery=False)

# Q-learning parameters
num_actions = env.action_space.n
num_states = env.observation_space.n
q_table = np.zeros((num_states, num_actions))

alpha = 0.8        # Learning rate
gamma = 0.95       # Discount factor
max_epsilon = 1.0  # Exploration probability at start
min_epsilon = 0.01 # Minimum exploration probability
decay_rate = 0.001 # Exponential decay rate for exploration probability

# Training parameters
n_episodes = 5000
max_steps = 30

epsilon = max_epsilon
rewards = []

for episode in range(n_episodes):
    s = env.reset()  # Reset environment
    if isinstance(s, tuple):  # For gym>=0.26
        s = s[0]
    
    total_reward = 0
    
    for step in range(max_steps):
        # Exploration-exploitation tradeoff
        if random.uniform(0, 1) < epsilon:
            a = env.action_space.sample()  # Random action
        else:
            a = np.argmax(q_table[s, :])   # Action from Q-table

        # Take action and observe outcome
        result = env.step(a)
        if len(result) == 5:  # Gym>=0.26 returns (state, reward, terminated, truncated, info)
            s_new, r, terminated, truncated, info = result
            done = terminated or truncated
        else:  # Gym<0.26 returns (state, reward, done, info)
            s_new, r, done, info = result

        # Update Q-table
        q_table[s, a] = q_table[s, a] + alpha * (r + gamma * np.max(q_table[s_new, :]) - q_table[s, a])

        s = s_new
        total_reward += r

        if done:
            break

    # Decay epsilon
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
    rewards.append(total_reward)

print("Training finished.\n")
print("Final Q-table:")
print(q_table)


C:\Users\User\anaconda3\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Training finished.

Final Q-table:
[[0.73509189 0.77378094 0.77378094 0.73509189]
 [0.73509189 0.         0.81450625 0.77378094]
 [0.77378094 0.857375   0.77378094 0.81450625]
 [0.81450625 0.         0.77378094 0.77378093]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.         0.81450625]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.857375   0.95       0.         0.857375  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]
